name: biblioteca
description: A new Flutter project.

publish_to: "none" 



environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_svg: ^2.0.7 
  carousel_slider: ^4.0.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: "^0.13.1"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/book_Images/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
 